# Generated by Django 4.2.6 on 2023-12-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_remove_labelmodel_tasks'),
        ('tasks', '0002_alter_taskmodel_description_alter_taskmodel_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='labels',
            field=models.ManyToManyField(to='labels.labelmodel'),
        ),
    ]
