# Generated by Django 4.2.6 on 2023-12-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
